config/routes.rb
Grit::Application.routes.draw do
  resources :video_jobs

  resources :videos

  get "camera_tag_handler/create"

  root 'public#index'

  get '/about', to: 'public#about', as: :about
  get '/more', to: 'public#more', as: :more
  get '/share', to: 'public#share', as: :share

  post 'service/video_tag_handler', to: 'camera_tag_handler#create'

end

app/models/video_job.rb
class VideoJob < ActiveRecord::Base
  require 'youtube_it'
  require 'httparty'

  attr_accessor :video_url, :thumb_url

  URL_PREFIX='http://cameratag.com/videos/'
  VIDEO_EXT='mp4'
  THUMB_EXT='thumb'

  def video_url
    URL_PREFIX+self.uuid+"/#{self.quality}/"+VIDEO_EXT
  end

  def thumb_url
    URL_PREFIX+self.uuid+"/#{self.quality}/"+THUMB_EXT
  end

  def que
    perform
  end
  handle_asynchronously :que

  def perform
    # download remote video file to temporary file
    tf = Tempfile.new(self.uuid)
    url = self.video_url

    tf.binmode
    tf.write(HTTParty.get(url).body)
    tf.close

    # upload file using youtube
    @yt = YoutubeService.new
    @response = @yt.upload(path: tf.path, name: self.name)
    #store video info to database
    if @response
      @v = Video.find_or_initialize_by_key(
             key: @response.unique_id,
             name: self.name,
             email: self.email
            )
      unless @v.save!
        raise 'Error Saving key to database'
      end
    else
      raise 'Error uploading to youtube'
    end
    tf.unlink
  end

  def success(job)
    logger.info "SUCCESS NewVideo [SAVE] key: #{@response.unique_id}"
    self.destroy!
  end

  def error(job, exception)
    logger.error "ERROR NewVideo [SAVE] key: #{@response.unique_id} Exception: #{exception} Job: #{job.inspect}"
  end

end

app/controllers/video_jobs_controller.rb
class VideoJobsController < ApplicationController
  before_action :set_video_job, only: [:show, :edit, :update, :destroy]

  # GET /video_jobs
  # GET /video_jobs.json
  def index
    @video_jobs = VideoJob.all
  end

  # GET /video_jobs/1
  # GET /video_jobs/1.json
  def show
  end

  # GET /video_jobs/new
  def new
    @video_job = VideoJob.new
  end

  # GET /video_jobs/1/edit
  def edit
  end

  # POST /video_jobs
  # POST /video_jobs.json
  def create
    @video_job = VideoJob.new(video_job_params)

    respond_to do |format|
      if @video_job.save
        format.html { redirect_to @video_job, notice: 'Video job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video_job }
      else
        format.html { render action: 'new' }
        format.json { render json: @video_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_jobs/1
  # PATCH/PUT /video_jobs/1.json
  def update
    respond_to do |format|
      if @video_job.update(video_job_params)
        format.html { redirect_to @video_job, notice: 'Video job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_jobs/1
  # DELETE /video_jobs/1.json
  def destroy
    @video_job.destroy
    respond_to do |format|
      format.html { redirect_to video_jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_job
      @video_job = VideoJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_job_params
      params[:video_job]
    end
end

app/helpers/video_jobs_helper.rb
module VideoJobsHelper
end

app/views/video_jobs/_form.html.haml
= form_for @video_job do |f|
  - if @video_job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video_job.errors.count, "error")} prohibited this video_job from being saved:"
      %ul
        - @video_job.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/video_jobs/edit.html.haml
%h1 Editing video_job

= render 'form'

= link_to 'Show', @video_job
\|
= link_to 'Back', video_jobs_path

app/views/video_jobs/index.html.haml
%h1 Listing video_jobs

%table
  %tr
    %th
      Image
    %th
      UUID
    %th
      NAME
    %th
      EMAIl
    %th
      Video URL
    %th
      Thumb URL
    %th
    %th
    %th

  - @video_jobs.each do |video_job|
    %tr
      %td
        = image_tag(video_job.thumb_url, width: 89, height: 68)
      %td
        = video_job.uuid
      %td
        = video_job.name
      %td
        = video_job.email
      %td
        = link_to('video url', video_job.video_url)
      %td
        = link_to('thumb url', video_job.thumb_url)
      %td= link_to 'Show', video_job
      %td= link_to 'Edit', edit_video_job_path(video_job)
      %td= link_to 'Destroy', video_job, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video job', new_video_job_path

app/views/video_jobs/new.html.haml
%h1 New video_job

= render 'form'

= link_to 'Back', video_jobs_path

app/views/video_jobs/show.html.haml
%p#notice= notice

%table
  %tr
    %th
      UUID
    %th 
      STATE
    %th
      Video URL
    %th
      Thumb URL
  %tr
    %td
      = @video_job.uuid
    %td
      = @video_job.state
    %td
      = @video_job.video_url
    %td
      = @video_job.thumb_url


= link_to 'Edit', edit_video_job_path(@video_job)
\|
= link_to 'Back', video_jobs_path