config/routes.rb
Grit::Application.routes.draw do
  resources :video_jobs

  resources :videos

  get "camera_tag_handler/create"

  root 'public#index'

  get '/about', to: 'public#about', as: :about
  get '/more', to: 'public#more', as: :more
  get '/share', to: 'public#share', as: :share

  post 'service/video_tag_handler', to: 'camera_tag_handler#create'

end

app/models/video.rb
class Video < ActiveRecord::Base

  require 'youtube_it'

  attr_accessor :youtube_url, :thumb_url

  URL_PREFIX='//www.youtube.com/watch?v='
  THUMB_PREFIX='http://img.youtube.com/vi/'
  THUMB_SUFFIX='/hqdefault.jpg'

  def youtube_url
    URL_PREFIX+self.key
  end

  def thumb_url
    THUMB_PREFIX+self.key+THUMB_SUFFIX
  end

  def youtube_object
    @s = get_session
    @s.my_video(self.key)
  end

  def prettyprint_json
    @o = youtube_object
    "<pre>\n"+JSON.pretty_generate(@o)+"</pre>".html_safe
  end

  def youtube_embed
    video = youtube_object
    video.embed_html5
  end

  def get_session
    @yt ||= YoutubeService.new
    @session ||= @yt.setup_session
  end
 
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params[:video]
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th
    %th
      Key
    %th
      Name
    %th
      Email
    %th
      Youtube URL
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td
        = image_tag(video.thumb_url, width: 89, height: 68)
      %td
        = video.key
      %td
        = video.name
      %td
        = link_to video.email, "mailto:"+video.email if video.email
      %td
        = link_to 'youtube url', video.youtube_url
      %td= link_to 'Show', video
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice
- video = @video

= video.youtube_embed.html_safe

.container

  %table
    %tr
      %th{colspan: 2}
        Identifiers
    %tr
      %th
        Key:
      %td
        = video.key
    %tr
      %th{colspan: 2}
        Associated Owner
    %tr
      %th
        Name:
      %td
        = video.name
      %thv
        Email:
      %td
        = video.email
    %tr
      %th{colspan: 2}
        Share & Embed URLs
    %tr
      %th
        Thumbnail:
      %td
        = video.thumb_url
      %th
        Youtube URL:
      %td
        = video.youtube_url
      %th
        Youtube Embed
      %td
        = video.youtube_embed
    %tr
      %th{colspan: 2}
        Raw API Data
    %tr
      %th
        RAW JSON Object:
      %td
        = video.youtube_object
      %th
        Formatted JSON Oject:
      %td
        = video.prettyprint_json

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path