config/routes.rb
Grit::Application.routes.draw do
  resources :video_jobs

  resources :videos

  get "camera_tag_handler/create"

  root 'public#index'

  get '/about', to: 'public#about', as: :about
  get '/more', to: 'public#more', as: :more
  get '/share', to: 'public#share', as: :share

  post 'service/video_tag_handler', to: 'camera_tag_handler#create'

end

app/views/layouts/_carousel.html.erb
<!-- <section id="main-slider">
  <div class="flexslider">
    <ul class="slides">
      <li>
        <%= image_tag('slides/duckworth.png') %>
      </li>
      <li>
        <%= image_tag('slides/duckworth.png') %>
      </li>
      <li>
        <%= image_tag('slides/duckworth.png') %>
      </li>
    </ul>
  </div>
</section> -->

<section id="top-carousel">
  <ul id="boutique">
    <!-- Frame with minimal setup: -->
    <li>
      <a href="">
        <%= image_tag 'slides/duckworth.png', alt: '', width: '677', height: '339' %>
      </a>
    </li>
    <li>
      <a href="">
        <%= image_tag 'slides/carols.jpg', alt: '', width: '403', height: '275' %>
      </a>
    </li>
    <li>
      <a href="">
        <%= image_tag 'slides/gritovergift.jpg', alt: '', width: '600', height: '427' %>
      </a>
    </li>
    <li>
      <a href="">
        <%= image_tag 'slides/grit.jpg', alt: '', width: '600', height: '400' %>
      </a>
    </li>
  </ul> 
</section>

app/views/layouts/_endorsements.html.erb
<section id="endorsements">
  <div class="heading-l">
    <h2>
      <span>Endorsements</span>
    </h2>
  </div>
  <div class="flexslider">
    <ul class="slides">
      <li>
        <div class="endorsement">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed. Lorem ipsum dolor sit amet.
        </div>
        <span class="credit">-Some Wise Person</span>
      </li>
      <li>
        <div class="endorsement">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed.
        </div>
        <span class="credit">-Some Wise Person</span>
      </li>
      <li>
        <div class="endorsement">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        </div>
        <span class="credit">-Some Wise Person</span>
      </li>
    </ul>
  </div>
</section>

app/views/layouts/_footer.html.haml
%footer#footer
  .container
    %section#sponsors
      %h4
        Powered By
      %ul
        %li
          %a{href: ''}
            = image_tag "cameratag.png"
        .clearfix

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav#nav
  .navbar.navbar-inverse.navbar-fixed-top
    .navbar-inner
      .nav-border
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to '#thisisgrit', '/', class: 'navbar-brand'
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
/ add navigation links to this file
%li= nav_link_to 'About #thisisgrit', about_path
%li= nav_link_to 'Check Out More Videos', more_path
%li= nav_link_to 'Share Your Own Story', share_path

app/views/layouts/_video.html.haml
%figure.top_video.col-md-4
  .top_videos_img
    = image_tag("http://img.youtube.com/vi/#{video.key}/hqdefault.jpg")
    .hover_video
      %a{:href => "http://www.youtube.com/watch?v=#{video.key}", :class => 'light-video', 'data-gal' => 'prettyPhoto', :title => video.title}
      .player_like
        %span
          %i.fa.fa-eye-open
          = video.views
        %span
          %i.fa.fa-heart
          = video.likes
  %h4
    %a{href: "http://www.youtube.com/watch?v=#{video.key}"}
  .hover_video
    %a{:href => "http://www.youtube.com/watch?v=#{video.key}", :class => 'light-video', 'data-gal' => 'prettyPhoto', :title => video.title}
    .player_like
      %span
        %i.fa.fa-eye-open
        = video.views
      %span
        %i.fa.fa-heart
        = video.likes

app/views/layouts/_videos.html.haml
%section#top-videos.top_videos
  .heading-l
    %h2
      %span Top Videos

  - for video in @videos

    .top_video_listing
      %figure.top_video.col-md-4
        .top_videos_img
          = image_tag("http://img.youtube.com/vi/#{video.key}/hqdefault.jpg")
          .hover_video
            %a{:href => "http://www.youtube.com/watch?v=#{video.key}", :class => 'light-video', 'data-gal' => 'prettyPhoto', :title => video.title}
            .player_like
              %span
                %i.fa.fa-eye-open
                = video.views
              %span
                %i.fa.fa-heart
                = video.likes
        %h4
          %a{href: "http://www.youtube.com/watch?v=#{video.key}"}
        .hover_video
          %a{:href => "http://www.youtube.com/watch?v=#{video.key}", :class => 'light-video', 'data-gal' => 'prettyPhoto', :title => 'Click to launch video'}
          .player_like
            %span
              %i.fa.fa-eye-open
              = video.views
            %span
              %i.fa.fa-heart
              = video.likes
  .clearfix

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'Grit'
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %meta{name: 'description', content: "#{content_for?(:description) ? yield(:description) : 'Grit'}"}
    %meta{name: 'author', content: ''}

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//cameratag.com/1.9/cameratag.js"
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'

    %main{role: "main"}
      = render 'layouts/messages'
      = yield
    = render partial: "layouts/footer"